cloud:
  aws:
    region:
      static: us-east-1
      auto: false
    credentials:
      access-key: 
      secret-key: 
    end-point:
      uri: https://sqs.us-east-1.amazonaws.com/390425570549/demo-queue
